// <auto-generated />
using System;
using LevelUpCommunity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LevelUpCommunity.Migrations
{
    [DbContext(typeof(LevelUpCommunityContext))]
    [Migration("20250225135304_init3.1")]
    partial class init31
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LevelUpCommunity.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("EventId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("LevelUpCommunity.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberId"));

                    b.Property<string>("MemberEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("LevelUpCommunity.Models.MemberEvent", b =>
                {
                    b.Property<int>("MemberEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemberEventId"));

                    b.Property<int>("EventIdFk")
                        .HasColumnType("int");

                    b.Property<int>("MemberIdFk")
                        .HasColumnType("int");

                    b.HasKey("MemberEventId");

                    b.HasIndex("EventIdFk");

                    b.HasIndex("MemberIdFk");

                    b.ToTable("MemberEvents");
                });

            modelBuilder.Entity("LevelUpCommunity.Models.MemberEvent", b =>
                {
                    b.HasOne("LevelUpCommunity.Models.Event", "Event")
                        .WithMany("MemberEvents")
                        .HasForeignKey("EventIdFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelUpCommunity.Models.Member", "Member")
                        .WithMany("MemberEvents")
                        .HasForeignKey("MemberIdFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LevelUpCommunity.Models.Event", b =>
                {
                    b.Navigation("MemberEvents");
                });

            modelBuilder.Entity("LevelUpCommunity.Models.Member", b =>
                {
                    b.Navigation("MemberEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
